name: Build docker images

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

env:
  GIT_LFS_SKIP_SMUDGE: 1

jobs:
  docker:
    runs-on: [ubuntu-22.04]
    needs: [checks]
    env:
      GIT_LFS_SKIP_SMUDGE: 1
      REGISTRY_URL: ghcr.io
    strategy:
      fail-fast: false
      matrix:
        docker:
          - name: Build Specs image
            image: specs
            path: specs
          - name: Build Docs image
            image: docs
            path: docs
          - name: Build Docs image
            image: community
            path: community

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: ${{ matrix.docker.name }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ env.REGISTRY_URL }}/anoma/namada-docs:${{ matrix.docker.image }}-main
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "TARGET=${{ matrix.docker.path }}"

  checks:
    runs-on: [ubuntu-22.04]
    strategy:
      fail-fast: false
      matrix:
        make:
          - name: docs
            path: docs
          # - name: specs
          #   path: specs
          - name: community
            path: community

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --offline packages/${{ matrix.make.path }}/pages/